### ISSUE TITLE
Introduction flow (Figma)

### ISSUE THREAD

**Issue by konstantinlob** [konstantinlob/What-am-I-listening-to#13]
Our project does not yet have an introduction for new users. This introduction has already been designed in Fimga (see image below). Create the introduction page under the path "/introduction".

![image](https://user-images.githubusercontent.com/23258120/192777204-14d2bdc2-a844-4382-bce9-002de1d28056.png)

**Comment by markus-gx** [comment]
You can assign this to me ;) Figma link to download the images? 
Should we bump to Nuxt RC.11 too?

**Comment by JuliusJaenchen** [comment]
Hey @markus-gx, Thanks for your interest!
Here's [our Figma Page](https://www.figma.com/file/q2gzCeo2MIHHkVQxvS7v6o/What-am-I-listening-to%3F?node-id=0%3A1 ) (It's still a work in progress :)). We're all new to Nuxt, so feel free to bump it up to RC 11 if it's not a hassle.

**Comment by markus-gx** [comment]
> Hey @markus-gx, Thanks for your interest!
> Here's [our Figma Page](https://www.figma.com/file/q2gzCeo2MIHHkVQxvS7v6o/What-am-I-listening-to%3F?node-id=0%3A1) (It's still a work in progress :)). We're all new to Nuxt, so feel free to bump it up to RC 11 if it's not a hassle.

Thanks; Quick question: Why haven't u used nuxtjs/tailwindcss ? The official Module for TailwindCSS?

**Comment by JuliusJaenchen** [comment]
Cool! I was not aware that existed, thanks for bringing it up. You're very welcome to switch our current tailwind setup out for nuxtjs/tailwindcss
